import { useEffect, useState } from "react";
import { Box, Container, IconButton, Stack, Typography } from "@mui/material";
import { ArrowBack, ArrowForward } from "@mui/icons-material";
import meetingImage from "../../assets/carousel-scout-meeting.jpg";
import teamworkImage from "../../assets/carousel-scout-teamwork.jpg";
import campImage from "../../assets/carousel-scout-camp.jpg";

const slides = [
  { image: meetingImage, eyebrow: "FELLOWSHIP", title: "Belong to something bigger.", text: "Scouting creates friendships, confidence and a shared sense of purpose that lasts far beyond every gathering." },
  { image: teamworkImage, eyebrow: "LEARNING BY DOING", title: "Skills become character.", text: "Hands-on challenges develop self-reliance, teamwork and the calm readiness to help when it matters most." },
  { image: campImage, eyebrow: "ADVENTURE", title: "Curiosity leads the way.", text: "Outdoor experiences bring young people closer to nature, one another and the values they carry into life." },
];

export default function ScoutCarousel() {
  const [active, setActive] = useState(0); const go = (step) => setActive((current) => (current + step + slides.length) % slides.length);
  useEffect(() => { const timer = setInterval(() => go(1), 6000); return () => clearInterval(timer); }, []);
  return <Box component="section" aria-label="Scouting highlights" sx={{ py: { xs: 7, md: 11 }, bgcolor: "#2b113f", color: "white" }}><Container maxWidth="lg"><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ md: "end" }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="overline" fontWeight={900} sx={{ color: "#d8b9ed", letterSpacing: ".18em" }}>The scouting experience</Typography><Typography variant="h2" fontWeight={950} sx={{ fontSize: { xs: "2.25rem", md: "3.7rem" }, letterSpacing: "-.045em" }}>Prepared for every adventure.</Typography></Box><Stack direction="row" spacing={1}><IconButton onClick={() => go(-1)} aria-label="Previous image" sx={{ color: "white", border: "1px solid rgba(255,255,255,.3)" }}><ArrowBack /></IconButton><IconButton onClick={() => go(1)} aria-label="Next image" sx={{ color: "white", border: "1px solid rgba(255,255,255,.3)" }}><ArrowForward /></IconButton></Stack></Stack><Box sx={{ position: "relative", minHeight: { xs: 520, sm: 570, md: 620 }, borderRadius: { xs: 3, md: 5 }, overflow: "hidden" }}>{slides.map((slide, index) => <Box key={slide.title} role="group" aria-hidden={index !== active} sx={{ position: "absolute", inset: 0, opacity: index === active ? 1 : 0, transform: index === active ? "scale(1)" : "scale(1.03)", transition: "opacity .7s ease, transform 1s ease", backgroundImage: `linear-gradient(0deg,rgba(24,7,36,.92),rgba(24,7,36,.05) 70%),url(${slide.image})`, backgroundSize: "cover", backgroundPosition: "center" }}><Box sx={{ position: "absolute", left: { xs: 24, md: 56 }, right: { xs: 24, md: "auto" }, bottom: { xs: 34, md: 52 }, maxWidth: 650 }}><Typography variant="overline" fontWeight={900} sx={{ color: "#d8b9ed", letterSpacing: ".16em" }}>{slide.eyebrow}</Typography><Typography variant="h3" fontWeight={950} sx={{ mt: .5, fontSize: { xs: "2rem", sm: "2.8rem", md: "3.7rem" }, letterSpacing: "-.04em" }}>{slide.title}</Typography><Typography sx={{ mt: 1.5, fontSize: { xs: 16, md: 19 }, lineHeight: 1.7, color: "rgba(255,255,255,.82)" }}>{slide.text}</Typography></Box></Box>)}</Box><Stack direction="row" spacing={1} justifyContent="center" sx={{ mt: 2.5 }}>{slides.map((slide, index) => <Box component="button" key={slide.title} onClick={() => setActive(index)} aria-label={`Show slide ${index + 1}`} sx={{ width: index === active ? 34 : 10, height: 10, p: 0, border: 0, borderRadius: 999, cursor: "pointer", bgcolor: index === active ? "white" : "rgba(255,255,255,.35)", transition: "width .25s" }} />)}</Stack></Container></Box>;
}
