import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, Autocomplete, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, InputAdornment, MenuItem, Paper, Stack, TextField, Tooltip, Typography } from "@mui/material";
import { CancelOutlined, DownloadOutlined, EmailOutlined, PaymentsOutlined, ReceiptLongOutlined, RefreshOutlined } from "@mui/icons-material";
import API from "../../api/axios";
import { DataTable, PageHeader, StatCard } from "../../components/common";
import { getStoredUser } from "../../utils/auth";

const today = () => new Date().toISOString().slice(0, 10);
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(value || 0);
const date = (value) => value ? new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";
const messageOf = (error, fallback) => error.response?.data?.message || error.message || fallback;

export default function Receipts() {
  const isAdmin = getStoredUser()?.role === "admin";
  const [receipts, setReceipts] = useState([]); const [members, setMembers] = useState([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [status, setStatus] = useState("all"); const [memberFilter, setMemberFilter] = useState(null);
  const [form, setForm] = useState({ member: null, title: "", amount: "", paidOn: today(), paymentMode: "online_transfer", paymentReference: "", notes: "" });
  const [voidTarget, setVoidTarget] = useState(null); const [voidReason, setVoidReason] = useState("");

  const load = useCallback(async () => { setLoading(true); setError(""); try { const [{ data }, memberResponse] = await Promise.all([API.get("/receipts", { params: { status, ...(memberFilter ? { memberId: memberFilter._id } : {}) } }), isAdmin ? API.get("/members") : Promise.resolve(null)]); setReceipts(data.receipts || []); if (memberResponse) { const list = memberResponse.data.members || memberResponse.data.data || memberResponse.data || []; setMembers((Array.isArray(list) ? list : []).filter((member) => member.status === "active")); } } catch (requestError) { setError(messageOf(requestError, "Unable to load receipts")); } finally { setLoading(false); } }, [isAdmin, memberFilter, status]);
  useEffect(() => { const id = setTimeout(load, 0); return () => clearTimeout(id); }, [load]);

  const setField = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const create = async () => { setError(""); setNotice(""); if (!form.member) return setError("Choose a member"); if (!form.title.trim()) return setError("Enter what this payment is for"); if (!form.amount || Number(form.amount) <= 0) return setError("Enter a valid amount greater than zero"); if (!form.paidOn) return setError("Choose the payment date"); if (form.paymentMode === "online_transfer" && !form.paymentReference.trim()) return setError("Enter the online transaction reference"); setSaving(true); try { const { data } = await API.post("/receipts", { memberId: form.member._id, title: form.title, amount: Number(form.amount), paidOn: form.paidOn, paymentMode: form.paymentMode, paymentReference: form.paymentReference, notes: form.notes }); setNotice(data.message); setForm({ member: null, title: "", amount: "", paidOn: today(), paymentMode: "online_transfer", paymentReference: "", notes: "" }); await load(); } catch (requestError) { setError(messageOf(requestError, "Unable to generate receipt")); } finally { setSaving(false); } };
  const download = async (receipt) => { try { const response = await API.get(`/receipts/${receipt._id}/pdf`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${receipt.receiptNumber}.pdf`; anchor.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(messageOf(requestError, "Unable to download receipt")); } };
  const resend = async (receipt) => { setError(""); setNotice(""); try { const { data } = await API.post(`/receipts/${receipt._id}/resend`); setNotice(data.message); await load(); } catch (requestError) { setError(messageOf(requestError, "Unable to email receipt")); } };
  const confirmVoid = async () => { if (voidReason.trim().length < 3) return; try { const { data } = await API.patch(`/receipts/${voidTarget._id}/void`, { reason: voidReason }); setNotice(data.message); setVoidTarget(null); setVoidReason(""); await load(); } catch (requestError) { setError(messageOf(requestError, "Unable to void receipt")); } };

  const issued = receipts.filter((receipt) => receipt.status === "issued");
  const total = useMemo(() => issued.reduce((sum, receipt) => sum + receipt.amount, 0), [issued]);
  const columns = [
    { id: "receiptNumber", label: "Receipt", minWidth: 150, render: (row) => <Box><Typography fontWeight={900} color="primary.main">{row.receiptNumber}</Typography><Typography variant="caption" color="text.secondary">Issued {date(row.createdAt)}</Typography></Box> },
    ...(isAdmin ? [{ id: "member", label: "Member", minWidth: 190, render: (row) => <Box><Typography fontWeight={800}>{row.member?.name || "Unknown member"}</Typography><Typography variant="caption" color="text.secondary">{row.member?.patrol || "—"} · {row.member?.itsId || "—"}</Typography></Box> }] : []),
    { id: "title", label: "Towards", minWidth: 190 },
    { id: "paidOn", label: "Payment date", minWidth: 140, render: (row) => date(row.paidOn) },
    { id: "paymentMode", label: "Mode", minWidth: 145, render: (row) => row.paymentMode === "online_transfer" ? "Online transfer" : "Cash" },
    { id: "amount", label: "Amount", minWidth: 130, render: (row) => <Typography fontWeight={900}>{money(row.amount)}</Typography> },
    { id: "status", label: "Status", minWidth: 110, render: (row) => <Chip size="small" label={row.status === "void" ? "Void" : "Issued"} color={row.status === "void" ? "default" : "success"} /> },
    { id: "actions", label: "Actions", minWidth: isAdmin ? 150 : 70, render: (row) => <Stack direction="row"><Tooltip title="Download PDF"><IconButton onClick={() => download(row)}><DownloadOutlined /></IconButton></Tooltip>{isAdmin && row.status === "issued" && <><Tooltip title="Email again"><IconButton onClick={() => resend(row)}><EmailOutlined /></IconButton></Tooltip><Tooltip title="Void receipt"><IconButton color="error" onClick={() => setVoidTarget(row)}><CancelOutlined /></IconButton></Tooltip></>}</Stack> },
  ];

  return <Box><PageHeader title="Receipts" subtitle={isAdmin ? "Generate, download and email official payment receipts to members." : "View and download every payment receipt issued to you."} />
    {error && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError("")}>{error}</Alert>}{notice && <Alert severity="success" sx={{ mb: 2 }} onClose={() => setNotice("")}>{notice}</Alert>}
    {isAdmin && <Paper sx={{ mb: 3, p: { xs: 2, md: 3 }, border: "1px solid", borderColor: "divider" }}><Stack direction="row" spacing={1.5} alignItems="center" sx={{ mb: 2.5 }}><Box sx={{ width: 46, height: 46, display: "grid", placeItems: "center", borderRadius: 2, bgcolor: "#F2E9F8", color: "#622599" }}><ReceiptLongOutlined /></Box><Box><Typography variant="h6" fontWeight={900}>Generate payment receipt</Typography><Typography variant="body2" color="text.secondary">The PDF is saved to the member&apos;s account and emailed automatically.</Typography></Box></Stack><Grid container spacing={2}>
      <Grid size={{ xs: 12, md: 6 }}><Autocomplete options={members} value={form.member} onChange={(_, value) => setForm((current) => ({ ...current, member: value }))} getOptionLabel={(option) => `${option.name} · ${option.itsId || option.patrol}`} renderInput={(params) => <TextField {...params} label="Member" required helperText={form.member?.email ? `Receipt will be emailed to ${form.member.email}` : form.member ? "This member has no email; the receipt will still be saved." : "Search by member name or ITS ID"} />} /></Grid>
      <Grid size={{ xs: 12, md: 6 }}><TextField fullWidth required label="Receipt title / payment towards" value={form.title} onChange={setField("title")} placeholder="e.g. Annual membership fee" inputProps={{ maxLength: 120 }} /></Grid>
      <Grid size={{ xs: 12, sm: 6, md: 3 }}><TextField fullWidth required label="Amount" type="number" value={form.amount} onChange={setField("amount")} inputProps={{ min: .01, step: .01 }} InputProps={{ startAdornment: <InputAdornment position="start">₹</InputAdornment> }} /></Grid>
      <Grid size={{ xs: 12, sm: 6, md: 3 }}><TextField fullWidth required label="Payment date" type="date" value={form.paidOn} onChange={setField("paidOn")} inputProps={{ max: today() }} InputLabelProps={{ shrink: true }} /></Grid>
      <Grid size={{ xs: 12, sm: 6, md: 3 }}><TextField fullWidth select required label="Payment mode" value={form.paymentMode} onChange={(event) => setForm((current) => ({ ...current, paymentMode: event.target.value, paymentReference: event.target.value === "cash" ? "" : current.paymentReference }))}><MenuItem value="online_transfer">Online transfer</MenuItem><MenuItem value="cash">Cash</MenuItem></TextField></Grid>
      <Grid size={{ xs: 12, sm: 6, md: 3 }}><TextField fullWidth required={form.paymentMode === "online_transfer"} disabled={form.paymentMode === "cash"} label="Transaction reference" value={form.paymentReference} onChange={setField("paymentReference")} placeholder="UTR / transaction ID" /></Grid>
      <Grid size={{ xs: 12, md: 9 }}><TextField fullWidth label="Notes (optional)" value={form.notes} onChange={setField("notes")} inputProps={{ maxLength: 500 }} /></Grid><Grid size={{ xs: 12, md: 3 }}><Button fullWidth size="large" variant="contained" onClick={create} disabled={saving} startIcon={saving ? <CircularProgress size={20} color="inherit" /> : <ReceiptLongOutlined />} sx={{ height: 56 }}>{saving ? "Generating…" : "Generate & email"}</Button></Grid>
    </Grid></Paper>}
    <Grid container spacing={2} sx={{ mb: 3 }}><Grid size={{ xs: 12, sm: 4 }}><StatCard title="Receipts" value={receipts.length} icon={<ReceiptLongOutlined />} color="primary" loading={loading} /></Grid><Grid size={{ xs: 12, sm: 4 }}><StatCard title="Issued amount" value={money(total)} icon={<PaymentsOutlined />} color="success" loading={loading} /></Grid><Grid size={{ xs: 12, sm: 4 }}><StatCard title={isAdmin ? "Emails sent" : "Available PDFs"} value={isAdmin ? receipts.filter((item) => item.emailStatus === "sent").length : issued.length} icon={isAdmin ? <EmailOutlined /> : <DownloadOutlined />} color="warning" loading={loading} /></Grid></Grid>
    <Paper sx={{ p: 2, mb: 2, border: "1px solid", borderColor: "divider" }}><Stack direction={{ xs: "column", md: "row" }} spacing={2} alignItems={{ md: "center" }}><TextField select size="small" label="Status" value={status} onChange={(event) => setStatus(event.target.value)} sx={{ minWidth: 170 }}><MenuItem value="all">All receipts</MenuItem><MenuItem value="issued">Issued</MenuItem><MenuItem value="void">Void</MenuItem></TextField>{isAdmin && <Autocomplete size="small" options={members} value={memberFilter} onChange={(_, value) => setMemberFilter(value)} getOptionLabel={(option) => option.name} sx={{ minWidth: 240 }} renderInput={(params) => <TextField {...params} label="Filter by member" />} />}<Button startIcon={<RefreshOutlined />} onClick={load} sx={{ ml: { md: "auto" } }}>Refresh</Button></Stack></Paper>
    <DataTable columns={columns} rows={receipts} loading={loading} getRowId={(row) => row._id} defaultOrderBy="createdAt" defaultOrder="desc" emptyTitle="No receipts found" emptyDescription={isAdmin ? "Generate the first payment receipt using the form above." : "Receipts issued to you will appear here."} />
    <Dialog open={Boolean(voidTarget)} onClose={() => setVoidTarget(null)} fullWidth maxWidth="xs"><DialogTitle>Void {voidTarget?.receiptNumber}?</DialogTitle><DialogContent><Alert severity="warning" sx={{ mb: 2 }}>The receipt remains in the audit history and its PDF will be marked VOID.</Alert><TextField fullWidth autoFocus label="Reason" value={voidReason} onChange={(event) => setVoidReason(event.target.value)} multiline minRows={2} inputProps={{ maxLength: 300 }} /></DialogContent><DialogActions><Button onClick={() => setVoidTarget(null)}>Cancel</Button><Button color="error" variant="contained" disabled={voidReason.trim().length < 3} onClick={confirmVoid}>Void receipt</Button></DialogActions></Dialog>
  </Box>;
}
